"""add friend sessions

Revision ID: 1d483c803711
Revises: a2f25f79a34a
Create Date: 2026-05-06 19:36:16.958203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d483c803711'
down_revision: Union[str, None] = 'a2f25f79a34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('friend_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('movies', sa.JSON(), nullable=True),
    sa.Column('owner_votes', sa.JSON(), nullable=True),
    sa.Column('friend_votes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_sessions_friend_user_id'), 'friend_sessions', ['friend_user_id'], unique=False)
    op.create_index(op.f('ix_friend_sessions_owner_user_id'), 'friend_sessions', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_sessions_owner_user_id'), table_name='friend_sessions')
    op.drop_index(op.f('ix_friend_sessions_friend_user_id'), table_name='friend_sessions')
    op.drop_table('friend_sessions')
    # ### end Alembic commands ###
