"""add recommendations

Revision ID: 74d2986c8918
Revises: 1b294eb47618
Create Date: 2026-05-05 20:02:22.065834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d2986c8918'
down_revision: Union[str, None] = '1b294eb47618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(length=300), nullable=False),
    sa.Column('movie_year', sa.Integer(), nullable=True),
    sa.Column('movie_genre', sa.String(length=300), nullable=True),
    sa.Column('movie_poster_url', sa.String(length=1000), nullable=True),
    sa.Column('movie_runtime_min', sa.Integer(), nullable=True),
    sa.Column('movie_rating_imdb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_recommendations_user_movie')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_movie_id'), 'recommendations', ['movie_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_movie_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
